/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "C:\EMBARCADERO\Proyectos\021-appCupones\Win32\Debug\tCuponDetalle"
(
   "FKSA_AUTOINC" AUTOINC,
   "FKSA_CUPON_INI" VARCHAR(12),
   "FKSA_CUPON_FIN" VARCHAR(12),
   "FKSA_FACTURA" VARCHAR(30),
   "FKSA_CAJA_NOMBRE" VARCHAR(30),
   "FKSA_CAJA_SERIE" VARCHAR(20),
   "FKSA_CLIENTE_COD" VARCHAR(15),
   "FKSA_CLIENTE_NOM" VARCHAR(80),
   "FKSA_CLIENTE_TLF" VARCHAR(40),
   "FKSA_ITEMS" INTEGER,
   "FKSA_CANT_CUPONES" INTEGER,
   "FKSA_FECHA" DATE,
   "FKSA_TOTAL_BS" MONEY,
   "FKSA_TOTAL_US" MONEY,
   "FKSA_TASA" MONEY,
   "FKSA_HORA" TIME,
   "FKSA_AUTOINC_OPERACION" INTEGER,
   "FKSA_TIPOREG" INTEGER,
PRIMARY KEY ("FKSA_AUTOINC") COMPRESS NONE
LOCALE CODE 8202
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "FKSA_KEYOPERACION" ON "C:\EMBARCADERO\Proyectos\021-appCupones\Win32\Debug\tCuponDetalle" ("FKSA_AUTOINC_OPERACION");
